name: "Cloudflare Cache Purge"

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - webhook

env:
  ZONE_NAME: cssnr.com

jobs:
  cache:
    name: "Cache"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Purge Cache"
        uses: cssnr/cf-purge-cache-action@v2
        if: ${{ env.CLOUDFLARE_TOKEN && env.ZONE_NAME }}
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        with:
          domains: ${{ env.ZONE_NAME }}
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
